export const DESKTOP_LAYOUT = {
    topHeader: {
        subtitleBoxWidth: 420,
        subtitleBoxHeight: 92,
        subtitleBoxYOffset: -8,
        nameYOffset: -24,
        subtitleTextOffsetX: 34,
        subtitleTextOffsetY: 28,
        nameStyle: {
            font: "700 158px Inter, Segoe UI, Arial, sans-serif",
            color: "rgba(242, 252, 249, 0.98)",
        },
        subtitlePanel: {
            radius: 46,
            fill: "rgba(255, 255, 255, 0.09)",
            stroke: "rgba(255, 255, 255, 0.22)",
        },
        subtitleStyle: {
            font: "600 34px Inter, Segoe UI, Arial, sans-serif",
            color: "rgba(232, 247, 242, 0.95)",
        },
    },
    mainPanels: {
        leftWidthRatio: 0.6,
        columnGap: 34,
        topPanelYOffset: 176,
        topPanelHeight: 620,
        leftPanel: {
            fill: "rgba(4, 10, 18, 0.58)",
            stroke: "rgba(255, 255, 255, 0.2)",
        },
        rightPanel: {
            fill: "rgba(7, 14, 24, 0.6)",
            stroke: "rgba(255, 255, 255, 0.18)",
        },
        aboutTitle: {
            text: "ABOUT",
            offsetX: 42,
            offsetY: 36,
            style: {
                font: "600 44px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(176, 244, 224, 0.95)",
            },
        },
        intro: {
            offsetX: 42,
            startY: 114,
            widthInset: 84,
            lineHeight: 68,
            maxLines: 2,
            lineGap: 14,
            style: {
                font: "500 52px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(243, 252, 249, 0.98)",
                shadowStrength: 0.56,
            },
        },
        keyword: {
            offsetX: 42,
            offsetY: 468,
            style: {
                font: "500 31px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(194, 220, 230, 0.92)",
            },
        },
        glanceTitle: {
            text: "AT A GLANCE",
            offsetX: 38,
            offsetY: 36,
            style: {
                font: "600 44px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(176, 244, 224, 0.95)",
            },
        },
        glanceSummary: {
            offsetX: 38,
            educationY: 112,
            workY: 180,
            widthInset: 76,
            lineHeight: 54,
            maxLines: 2,
            style: {
                font: "600 42px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(243, 252, 249, 0.98)",
            },
        },
        glanceDetail: {
            offsetX: 38,
            firstY: 410,
            secondY: 456,
            style: {
                font: "500 30px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(199, 225, 235, 0.93)",
            },
        },
    },
    timeline: {
        panelYOffset: 34,
        panelHeight: 460,
        panel: {
            fill: "rgba(5, 11, 20, 0.6)",
            stroke: "rgba(255, 255, 255, 0.2)",
        },
        title: {
            text: "TIMELINE",
            offsetX: 40,
            offsetY: 32,
            style: {
                font: "600 44px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(176, 244, 224, 0.95)",
            },
        },
        cards: {
            maxVisibleCards: 3,
            widthGapBase: 100,
            startY: 94,
            startXInset: 40,
            height: 328,
            gap: 22,
            panel: {
                radius: 24,
                fill: "rgba(255, 255, 255, 0.06)",
                stroke: "rgba(255, 255, 255, 0.2)",
            },
            organization: {
                offsetX: 24,
                offsetY: 24,
                widthInset: 48,
                lineHeight: 42,
                maxLines: 2,
                style: {
                    font: "600 33px Inter, Segoe UI, Arial, sans-serif",
                    color: "rgba(242, 252, 249, 0.98)",
                },
            },
            role: {
                offsetX: 24,
                offsetY: 122,
                widthInset: 48,
                lineHeight: 37,
                maxLines: 3,
                style: {
                    font: "500 28px Inter, Segoe UI, Arial, sans-serif",
                    color: "rgba(195, 222, 233, 0.95)",
                },
            },
            period: {
                offsetX: 24,
                bottomInset: 58,
                style: {
                    font: "600 27px Inter, Segoe UI, Arial, sans-serif",
                    color: "rgba(152, 245, 221, 0.98)",
                },
            },
        },
    },
    footer: {
        panelYOffset: 30,
        sectionGap: 34,
        sectionsCount: 2,
        sectionPanel: {
            fill: "rgba(4, 10, 18, 0.56)",
            stroke: "rgba(255, 255, 255, 0.2)",
        },
        innerPadding: 40,
        sectionTitleY: 30,
        sectionTopPadding: 94,
        sectionBottomPadding: 28,
        titleStyle: {
            font: "700 44px Inter, Segoe UI, Arial, sans-serif",
            color: "rgba(176, 244, 224, 0.98)",
        },
        stackTitle: "TECH STACK",
        contactTitle: "CONTACT",
        skillPill: {
            gapX: 16,
            gapY: 16,
            maxRows: 2,
            minHeight: 76,
            maxHeight: 94,
            horizontalPadding: 24,
            textInsetX: 24,
            textWidthInset: 48,
            maxFontSize: 36,
            minFontSize: 24,
            fontWeight: 700,
            panel: {
                fill: "rgba(255, 255, 255, 0.11)",
                stroke: "rgba(255, 255, 255, 0.24)",
                lineWidth: 2.5,
            },
            textStyle: {
                font: "700 36px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(238, 251, 247, 0.99)",
            },
            textColor: "rgba(238, 251, 247, 0.99)",
        },
        contactPill: {
            gapX: 12,
            gapY: 14,
            rows: 3,
            minHeight: 74,
            maxHeight: 92,
            minWidth: 230,
            horizontalPadding: 18,
            textInsetX: 16,
            textWidthInset: 32,
            maxFontSize: 34,
            minFontSize: 22,
            fontWeight: 700,
            panel: {
                fill: "rgba(64, 231, 194, 0.22)",
                stroke: "rgba(64, 231, 194, 0.52)",
                lineWidth: 2.7,
            },
            textStyle: {
                font: "700 34px Inter, Segoe UI, Arial, sans-serif",
                color: "rgba(232, 252, 246, 0.99)",
            },
            textColor: "rgba(232, 252, 246, 0.99)",
        },
    },
} as const;
